<div align="center"> <h3><font color='cyan'>CSE 574 Sections C&D: Introduction to Machine Learning, Spring 2022 </font> 
<h1> Assignment 1 - Python Intro

<h3>Checkpoint: February 13, Sun, 11:59pm
<h2><font color='red'>Final Due Date: </font> February 20, Sun, 11:59pm</div>

Welcome to your first CSE 574 assignment! The goal of this assignment is to sharpen your programming skills needed for this class. It is focused on familiarizing yourself with Python and main data science libraries that will be used for other assignments as well.

There are a total of five parts. We will focus on basic Python functions, explore numpy, pandas and matplotlib libraries and analyze the real-world dataset.

If you are new to Python, check our [Python resources page](https://ubuffalo-my.sharepoint.com/:w:/g/personal/avereshc_buffalo_edu/ESoUg6v6aoJImaeWXy90SqMBiubxGGAkG7dhaNyhuBum_w?e=3Tlwbz) and our class demos.


### Submission

All the details you need for this assignment are located within this notebook. You are expected to follow every block and complete the task within the marks ``` # BEGIN_YOUR_CODE ``` and ```# END_YOUR_CODE```, as well as adding an Academic Integrity statement at the beginning within the marks ```# ADD YOUR ACADEMIC INTERGITY STATEMENT``` and ```# END OF YOUR ACADEMIC INTERGITY STATEMENT```. Do not modify or edit code beyond these lines. You can add helper functions in the new cells, if needed. We recommend completing the task within this .ipynb notebook, if needed you can convert it and submit as .py script. Try to make your code as clean and simple as possible and be sure to write your answers between the begin answer and end answer comments.

1. Submit at **UBLearns > Assignments**
2. The code of your implementations should be written in Python
3. All project files should be packed in a ZIP file named YOUR_FIRST_NAME_YOUR_LAST_NAME_assignment1.zip (e.g. alina_vereshchaka_assignment1.zip).
4. Your Jupyter notebook should be saved with the results. If you are submitting python scripts, after extracting the ZIP file and executing command python main.py in the first level directory, all the generated results and plots you used in your report should appear printed out in a clear manner.  
6. Include all the references that have been used to complete the assignment.

### Checkpoint Submission <font color='red'>[Due Date: Feb 13]</font>
Complete Part 1, Part 2 and Part 3 and submit the code in the ZIP file named YOUR_FIRST_NAME_YOUR_LAST_NAME_assignment1_checkpoint.zip. Checkpoint will be evaluated after the final submission.

### Final Submission <font color='red'>[Due Date: Feb 20]</font>
Complete all parts of the assignment and submit the code in the ZIP file named YOUR_FIRST_NAME_YOUR_LAST_NAME_assignment1_final.zip. You may add slight modification to your Checkpoint submission if needed.

**Assignment Outline**

| Part | Description | # of tasks | Points |
| --- | --- | --- | --- |
| [Part 1](#part1) | Basics | 10 | 20 |
| [Part 2](#part2) | Numpy Basics | 11 | 20 |
| [Part 3](#part3) | Algorithms | 2 | 20 |
| [Part 4](#part4) | Pandas Basics | 8 | 20 |
| [Part 5](#part5) | Matplotlib Basics | 9 | 20 |

    
### Academic Integrity

This assignment must be completed individually.
The standing policy of the Department is that all students involved in any academic integrity violation (e.g. plagiarism in any way, shape, or form) will receive an F grade for the course. The catalog describes plagiarism as “Copying or receiving material from any source and submitting that material as one’s own, without acknowledging and citing the particular debts to the source, or in any other manner representing the work of another as one’s own.”. Refer to the [Office of Academic Integrity](https://www.buffalo.edu/academic-integrity.html) for more details.

### <font color='red'>IMPORTANT NOTE</font>
In order to certify that you followed Academic Integrity policy while completing the assignment, please include the following statement as a comment block. In case you submit multiple files, add this statement at the beginning of each code file submitted: 

"I certify that the code and data in this assignment were generated independently, using only the tools and resources defined in the course and that I did not receive any external help, coaching or contributions during the production of this work."

Submissions without the academic integrity statement will not be evaluated and will receive a 0.

### Late Days Policy
You can use up to 7 late days throughout the course toward any assignments' checkpoint or final submission. You do not have to inform the instructor, as the late submission will be tracked in UBlearns.

### FAQ
>What does 'raise Exception("Not implemented yet")' mean?

Here we define a custom exception to highlight that the task is not implemented yet. Once you implement your code, ensure to remove this part.

>Can I add code beyond # BEGIN_YOUR_CODE parts.

Yes, you can add helper functions. Add them in the separate cell with the comments, why you need it


## START COMPLETING YOUR ASSIGNMENT HERE

In [14]:
# ADD YOUR ACADEMIC INTERGITY STATEMENT HERE AS A COMMENT BLOCK BELOW. CHECK IMPORTANT NOTE FOR MORE DETAILS.



I certify that the code and data in this assignment were generated independently, using only the tools and resources defined in the course and that I did not receive any external help, coaching or contributions during the production of this work.




# END OF YOUR ACADEMIC INTERGITY STATEMENT

<a id='part1'></a>
## Part 1 - Pyhton Basics [20 points]

The first part of this assignment gives you practice with python syntax. Follow the cells below for the instructions.

In [120]:
''' Hello
Print a word "Hello " 101 times
'''

# BEGIN_YOUR_CODE

print("hello "*101)


# END_YOUR_CODE

hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello 


In [121]:
''' Hello World
Using two variables hello and world defined below return 'Hello UB'. 
'''

hello  = 'hello'
world = 'ub'

# BEGIN_YOUR_CODE
print (hello.capitalize()+" "+world.upper())
# END_YOUR_CODE

Hello UB


In [122]:
''' Updating elements
Given a string my_list, update the third element to '2' and fourth element to '3', so the output is as follows: [0, 1, 2, 3, 4, 5]
'''

my_list = [0, 1, 'two', 'three', 4, 5]

# BEGIN_YOUR_CODE
my_list[2]=2
my_list[3]=3
print(my_list)
# END_YOUR_CODE

[0, 1, 2, 3, 4, 5]


In [123]:
'''Fibonacci Series
Print the first 12 Fibonacci numbers
'''

# BEGIN_YOUR_CODE
n=12
n1=0
n2=1
c=0

if n<=0:
    print("not possible")
    
elif n==0:
    print(n1)
    
else:
    while c<n:
        print(n1)
        sum=n1+n2
        n1=n2
        n2=sum
        c+=1
# END_YOUR_CODE

0
1
1
2
3
5
8
13
21
34
55
89


In [124]:
''' Reversing
Reverse the order of elements in a list given below, so the output is as follows: ['The Matrix Resurrections', 'The Matrix Revolutions', 'The Matrix Reloaded', 'The Matrix']
'''

list1 = ["The Matrix", "The Matrix Reloaded", "The Matrix Revolutions", "The Matrix Resurrections"]

# BEGIN_YOUR_CODE
print(list1[::-1])
# END_YOUR_CODE

['The Matrix Resurrections', 'The Matrix Revolutions', 'The Matrix Reloaded', 'The Matrix']


In [125]:
'''Concatenating strings
Concatenate strings in a list below, so the output is as follows: "python"
'''

list2 = ['p', 'y', 't', 'h', 'o', 'n']

# BEGIN_YOUR_CODE
list =''.join(list2)
print(list)
# END_YOUR_CODE

python


In [126]:
'''Numbering a list
Print a numbered list of the famous AI researchers using "enumerate()" function
'''

researchers = ['Yann LeCun', 'Yoshua Bengio', 'Geoffrey Hinton', 'Fei-Fei Li', 'Andrew Ng']

# BEGIN_YOUR_CODE
list1=[]
for i,j in enumerate(researchers,1):
    list1.append(i)
    list1.append(j)
print ((list1))
# END_YOUR_CODE

[1, 'Yann LeCun', 2, 'Yoshua Bengio', 3, 'Geoffrey Hinton', 4, 'Fei-Fei Li', 5, 'Andrew Ng']


In [127]:
'''Combining lists
Combine two lists given below using zip() fucntion and print out the result
'''

researchers = ['Yann LeCun', 'Yoshua Bengio', 'Geoffrey Hinton', 'Fei-Fei Li', 'Andrew Ng']
work = ['Facebook', 'Université de Montréal', 'University of Toronto', 'Stanford University', 'Landing AI']

# BEGIN_YOUR_CODE
for i,j in zip(researchers ,work):
    print((i,j))
  


# END_YOUR_CODE

('Yann LeCun', 'Facebook')
('Yoshua Bengio', 'Université de Montréal')
('Geoffrey Hinton', 'University of Toronto')
('Fei-Fei Li', 'Stanford University')
('Andrew Ng', 'Landing AI')


In [128]:
'''Print squares of even numbers and cubes of odd numbers for numbers from 1 till 12.
So the output comes in the form as follows: [1, 4, 27, 16, 125, 36, ....]
'''

# BEGIN_YOUR_CODE
list1=[]
for i in range(1,13):
    if i%2==0:
        list1.append(i*i)
    else:
         list1.append(i*i*i)
print(list1)
# END_YOUR_CODE

[1, 4, 27, 16, 125, 36, 343, 64, 729, 100, 1331, 144]


In [129]:
''' Sum function
Modify the function below to return a sum of a and b
'''

def add(a: int, b: int) -> int:
    
    # BEGIN_YOUR_CODE
    x=a+b
    return(x)
    raise Exception("Not implemented yet")

    # END_YOUR_CODE

We defined ```add_test``` to test your ```add``` function. For this function we ```import random``` library. This is a very commonly used package that helps to generate random values. For example:

``` python
random.randint(0, 100) #Returns any random integer from 0 to 100
```

In [130]:
import random

def add_test():
    a = random.randint(0, 9)
    b = random.randint(0, 9)
    result = add(a, b)

    return('Value of a is {0}, value of b is {1}, and their sum is {2}.'.format(a, b,result))

In [131]:
# Here we call our function 'add_test' to test your add function with random values
if __name__ == '__main__':
    print(add_test())

Value of a is 8, value of b is 2, and their sum is 10.


<a id='part2'></a>
## Part 2 - Numpy Basics [20 points]

In this section we will explore one of the most commonly used package - Numpy. You can refer to the [Official NumPy Guide](https://numpy.org/doc/stable/).

In [132]:
'''Import the numpy package
'''

# BEGIN_YOUR_CODE
import numpy as np
# END_YOUR_CODE

In [133]:
''' Random integers
Create an array of random integers from 0 to 50 with the length 10 using numpy random generator
'''

# BEGIN_YOUR_CODE
array = np.random.randint(50, size=(10))
# END_YOUR_CODE

print(array)

[34  0 25 24 26 43  8 37  2 34]


In [134]:
''' Slicing
Slice the above array and extract the first 2 elements, the last two elements, and all elements that are left in the middle.
'''

# BEGIN_YOUR_CODE
first_two = array[:2]
last_two = array[8:]
middle = array[2:8]
# END_YOUR_CODE

print('The first 2 elements are {0} \nThe last two elements are {1} \nElements in the middle are {2} '.format(first_two, last_two, middle))

The first 2 elements are [34  0] 
The last two elements are [ 2 34] 
Elements in the middle are [25 24 26 43  8 37] 


In [135]:
'''Split an array
For the above list 'array' split the list into 5 equal parts  and print it in the form
[array([1,2]), array([3,4]), array([5,6]), array([7,8]), array([9,10])]

'''

# BEGIN_YOUR_CODE
splittt = np.array_split(array,5)
print(splittt)
# END_YOUR_CODE

[array([34,  0]), array([25, 24]), array([26, 43]), array([ 8, 37]), array([ 2, 34])]


In [136]:
'''Generate two arrays of size 10 (integers randomly selected between 1 and 100). 
Print unique elements of array1 and common elements of both arrays separately
'''

# BEGIN_YOUR_CODE
array1 = np.random.randint(100,size=(10))
array2 = np.random.randint(100,size=(10))
unique_elements_array1 = np.unique(array1) 
common_elements_array1_array2 = np.intersect1d(array1,array2)
print(array1)
print(array2)
print(unique_elements_array1) 
print(common_elements_array1_array2)  
# END_YOUR_CODE

[93 99 66 69  8 27 35  3 88 37]
[36 93  0 20 29 72 43 74 92 27]
[ 3  8 27 35 37 66 69 88 93 99]
[27 93]


In [137]:
'''Changing dimensions
Convert your 1D array defined above to a 2D matrix and print its shape. The final output dimension should be 5x2.
'''

# BEGIN_YOUR_CODE
new2d=np.reshape(array,(5,2))
print(new2d)
# END_YOUR_CODE

[[34  0]
 [25 24]
 [26 43]
 [ 8 37]
 [ 2 34]]


In [138]:
'''Changing dimensions
Convert a matrix below to 1D array and print its dimension
'''

A = np.array([[1,2], [3,4], [5,6]])

# BEGIN_YOUR_CODE
newmat= A.flatten()
d=newmat.ndim
print(newmat)
print(d)
# END_YOUR_CODE

[1 2 3 4 5 6]
1


In [139]:
''' Matrices
Create two matrices A and B of size 5X6 and 6X5 respectively with random values from 0 to 1, and perform the dot product on them
'''

# BEGIN_YOUR_CODE
A =  np.random.random((5,6))
B =   np.random.random((6,5))
dot_product = np.dot(A,B)
# END_YOUR_CODE

print('\nMatrix A is \n{0} \nMatrix B is \n{1}, \nTheir product is \n{2}'.format(A, B, dot_product))


Matrix A is 
[[0.63732798 0.14448934 0.81647605 0.29769704 0.51771812 0.4553234 ]
 [0.96868642 0.51608084 0.44875199 0.73046014 0.18346637 0.67152071]
 [0.86520738 0.27080186 0.68938251 0.81511301 0.68767541 0.52307641]
 [0.04702582 0.4935126  0.18480465 0.32460264 0.20761727 0.40428985]
 [0.89690998 0.91171031 0.80239163 0.00389273 0.04685093 0.39552121]] 
Matrix B is 
[[0.61271653 0.81912379 0.43306174 0.24656179 0.82495971]
 [0.4215658  0.06003871 0.82132236 0.85835908 0.15223955]
 [0.40541475 0.1003387  0.62514684 0.70326202 0.3833765 ]
 [0.63029563 0.19232423 0.9022066  0.52262875 0.34476487]
 [0.53824833 0.61010535 0.50622686 0.78820578 0.050441  ]
 [0.1720215  0.43027082 0.54033828 0.49488852 0.41067775]], 
Their product is 
[[1.32704805 1.18167893 1.68178782 1.64434883 1.17652552]
 [1.66769519 1.41084088 2.23865555 1.85611058 1.58660599]
 [1.89765619 1.59552723 2.39422743 2.15748458 1.54980625]
 [0.69767588 0.44974437 1.15764142 1.09854209 0.47319317]
 [1.35490801 1.06944304 1

In [140]:
''' Maximum value
Return the maximum value present in each row of Matrix A created in the previous question. 
Result should come in the form: [row1_max row2_max row3_max row4_max row5_max]
'''

# BEGIN_YOUR_CODE
row1_max= np.amax(A[0])
row2_max= np.amax(A[1])
row3_max= np.amax(A[2])
row4_max= np.amax(A[3])
row5_max= np.amax(A[4])

max_value=[row1_max,row2_max,row3_max,row4_max,row5_max]

print(max_value)
# END_YOUR_CODE

[0.8164760502107526, 0.9686864166771254, 0.8652073786968626, 0.493512595595584, 0.9117103077486914]


In [141]:
''' Multiply the Matrix A from previous question with a scalar 3
'''

# BEGIN_YOUR_CODE

final=A*3
print(final)
# END_YOUR_CODE

[[1.91198394 0.43346803 2.44942815 0.89309111 1.55315436 1.36597019]
 [2.90605925 1.54824252 1.34625598 2.19138042 0.55039912 2.01456213]
 [2.59562214 0.81240558 2.06814752 2.44533902 2.06302622 1.56922922]
 [0.14107747 1.48053779 0.55441396 0.97380793 0.6228518  1.21286956]
 [2.69072993 2.73513092 2.4071749  0.01167818 0.14055278 1.18656362]]


In [142]:
''' Element-wise multiplication
Define two matrices A and B 2x4 with random values from 0 to 9. Perform element-wise multiplication of Matrices A and B
''' 

# BEGIN_YOUR_CODE
A = np.random.randint(0,10, (2,4))
B = np.random.randint(0,10, (2,4))
multiplicaiton = np.multiply(A,B)
# END_YOUR_CODE


print('\nMatrix A is \n{0} \nMatrix B is \n{1}, \nTheir element-wise multiplication is \n{2}'.format(A, B, multiplicaiton))


Matrix A is 
[[5 4 6 0]
 [7 2 8 3]] 
Matrix B is 
[[4 7 6 2]
 [1 9 1 9]], 
Their element-wise multiplication is 
[[20 28 36  0]
 [ 7 18  8 27]]


<a id='part3'></a>
## Part 3 - Algorithms [30 points]

### Euclidian Distance

Let point $p$ have Cartesian coordinates $(p_1,p_2)$ and let point $q$ have coordinates $(q_1,q_2)$. Then the distance between $p$ and $q$ is given by:
    $d(p,q) = \sqrt{(q_1-p_1)^2 + (q_2-p_2)^2}$.</math>

In [143]:
''' Euclidean distance
Using numpy library return the Euclidean distance between two locations, where the locations are pairs of numbers (e.g., (3, 5)) '''
import random
def euclidean_distance(loc1: int, loc2: int) -> float:

    # BEGIN_YOUR_CODE
    
    e_d= (((loc2[0]-loc1[0])**2+(loc2[1]-loc1[1])**2)**0.5)
    return e_d
    raise Exception("Not implemented yet")
    
    # END_YOUR_CODE

In [144]:
def euclidean_distance_test():
    random.seed(34)
    for _ in range(10):
        x1 = random.randint(0, 10)
        x2 = random.randint(0, 10)
        y1 = random.randint(0, 10)
        y2 = random.randint(0, 10)
        dist = euclidean_distance((x1, x2), (y1, y2))
    return('Loc1 is ({0}, {1}), loc2 is ({2}, {3}). Euclidian disctance is {4}.'.format(x1, x2, y1, y2, dist))

In [145]:
if __name__ == '__main__':
    print(euclidean_distance_test())

Loc1 is (5, 3), loc2 is (3, 7). Euclidian disctance is 4.47213595499958.


### String Operations

In [146]:
''' Alphabetically first word
Given a string, lowecase, sort our all words in the alphabetical order and return the word that comes first.
If the input text is an empty string, return an empty string or throw an error. '''

def first_word(text: str) -> str:
    
    # BEGIN_YOUR_CODE
       if text!='':
         h=text.split(' ')
         l=[]
         for i in h:
           j=i.lower()
           l.append(j)
         l.sort()
         return l[0] 
       else:
        raise Exception("Not implemented yet")

   # END_YOUR_CODE

In [147]:
def first_word_test():
    result0 = first_word('WelCome tO Ub')
    result1 = first_word('CSE574 IntRo to ML cLasS')
    result2 = first_word('SequenCes of DeCiSions')
    result3 = first_word('Wolf, Panther, Leopard, Dog, Cat')
    return result0, result1, result2, result3

In [148]:
if __name__ == '__main__':
    print(first_word_test())

('to', 'class', 'decisions', 'cat')


## Load from Drive*

*If you are using Goolge Colab, uncomment the following piece of code and verify the file using the command, if you can see your file ```museum.csv``` you are good to go.

In [44]:
# !pwd
# !ls

In [45]:
#from google.colab import drive
#drive.mount('/content/drive')
#%cd ..
#%cd /content/drive/MyDrive

<a id='part4'></a>
##  Part 4 - Pandas Basics [20 points]

Some important resources:

- [A Pandas guide](https://pandasguide.readthedocs.io/en/latest/) covers fundamental information about the package

- [Pandas Cheat Sheet](https://www.datacamp.com/community/blog/python-pandas-cheat-sheet)

In [46]:
'''Install and import pandas library
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

'Install and import pandas library\n'

In [47]:
'''Read given 'DataFile' and extract into Dataframe
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

"Read given 'DataFile' and extract into Dataframe\n"

In [48]:
'''Provide the main statistics about the entries of the dataset (mean, std, etc.)
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

'Provide the main statistics about the entries of the dataset (mean, std, etc.)\n'

In [49]:
''' Print shape of the dataset '''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

' Print shape of the dataset '

In [50]:
''' Return all the colums names'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

' Return all the colums names'

In [51]:
''' Print a list of museums types '''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

' Print a list of museums types '

In [52]:
''' Return insight about index(columns) of museum.csv '''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

' Return insight about index(columns) of museum.csv '

In [53]:
'''Print top 10 rows of the dataset'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

'Print top 10 rows of the dataset'

<a id='part5'></a>
## Matplotlib Basics [20 points]

Heatmaps are a useful plot tool which help us visualize the data density or distribution. Refer the below documentation for more details on heatmap.

[Matplotlib tutorial](https://machinelearningknowledge.ai/matplotlib-heatmap-complete-tutorial-for-beginners/)

**Note:** You can only use matplotlib library for the following tasks

In [54]:
''' Install and import matplotlib library
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

' Install and import matplotlib library\n'

In [55]:
''' Heatmap
Take any random numpy array of dimension 10x15 and plot a heatmap
'''

# BEGIN YOUR CODE

# END YOUR CODE

' Heatmap\nTake any random numpy array of dimension 10x15 and plot a heatmap\n'

In [56]:
'''For the given value x plot the function y = 1/x using list comprehension on y.
You can check https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions to learn how to use list comprehension
'''

x = range(25)

# BEGIN YOUR CODE

# END YOUR CODE

In [57]:
'''For the given value x plot the function y = x^2 using lambda function y.

Lambda function is a small anonymous function which consist of a single expression, and is usually used when we need the function for a smaller duration
https://realpython.com/python-lambda/
'''

x = range(25)

# BEGIN YOUR CODE

# END YOUR CODE


In [58]:
'''On one graph draw two lines:
1) Plot the function y = x^2 using lambda function y (use your code from above)
2) A scatter plot for y = x^3 using either list comprehension or lambda function for evaluating y
'''

x = range(25)

# BEGIN YOUR CODE

# END YOUR CODE

In [59]:
'''Create subplots showing graphs of tan and cot side by side of each other
the value of theta ranges from -30 to 30

HINT: You might want to utilize np.linespace() or np.arrange() to create smooth curves
'''

import math

# BEGIN YOUR CODE

# END YOUR CODE

In [60]:
'''Draw a line for given GPAs of students [3.5, 2.3, 3.8, 2.4, 2.9, 3.3] using markers
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

'Draw a line for given GPAs of students [3.5, 2.3, 3.8, 2.4, 2.9, 3.3] using markers\n'

In [61]:
''' Museum ("museum.csv"): total number of museums per type

Plot a bar graph which shows the total number of museums in USA corresponding to the museum type
'''

# BEGIN YOUR CODE

# END YOUR CODE

' Museum ("museum.csv"): total number of museums per type\n\nPlot a bar graph which shows the total number of museums in USA corresponding to the museum type\n'

In [62]:
''' Museum ("museum.csv"): total number of museums per state

Plot a graph which shows the total number of museums per each state ("State (Physical Location)")
'''

# BEGIN YOUR CODE

# END YOUR CODE

' Museum ("museum.csv"): total number of museums per state\n\nPlot a graph which shows the total number of museums per each state ("State (Physical Location)")\n'

#### Results analyzing

Analyze the graph and answer the following two questions:

**1) What is your inference from the above graph?**

*YOUR ANSWER:*

**2) Which state has the most number of museum?**

*YOUR ANSWER:*

**3) Which is the most common type of museum?**

*YOUR ANSWER:*


## References Used

**List below all the references you used to complete the assignment**

In [ ]:
W3schools.com
geeksforgeeks.com
